### ISSUE TITLE
Cancelling a Pod that does not exist in k8s any more triggers 500

### ISSUE THREAD

**Issue by danking** [hail-is/batch#22]
The relevant log message:

```
INFO:werkzeug:10.56.1.22 - - [08/Aug/2018 12:53:59] "POST /jobs/118/cancel HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/batch/server.py", line 181, in cancel_job
    job.cancel()
  File "/batch/server.py", line 88, in cancel
    self._cancel_pod()
  File "/batch/server.py", line 45, in _cancel_pod
    v1.delete_namespaced_pod(self._pod_name, 'default', kube.client.V1DeleteOptions())
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 9689, in delete_namespaced_pod
    (data) = self.delete_namespaced_pod_with_http_info(name, namespace, body, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 9789, in delete_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 387, in request
    body=body)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 256, in DELETE
    body=body)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '53098007-4bf1-4472-8812-26356c8ff118', 'Content-Type': 'application/json', 'Date': 'Wed, 08 Aug 2018 12:53:59 GMT', 'Content-Length': '194'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"job-118-h946w\" not found","reason":"NotFound","details":{"name":"job-118-h946w","kind":"pods"},"code":404}
```

**Comment by cseed** [comment]
I fixed this.
